//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Consulenza
    {
        public System.Guid IdConsulenza { get; set; }
        public Nullable<System.Guid> IdSocio { get; set; }
        public System.DateTime DataConsulenza { get; set; }
        public int IdTipologiaPratica { get; set; }
        public string DescrizioneConsulenza { get; set; }
        public Nullable<int> IdTipologiaContatto { get; set; }
        public string Nominativo { get; set; }
        public string Email { get; set; }
        public Nullable<int> IdComune { get; set; }
    
        public virtual Comune Comune { get; set; }
        public virtual Socio Socio { get; set; }
        public virtual TipologiaContatto TipologiaContatto { get; set; }
        public virtual TipologiaPratica TipologiaPratica { get; set; }
    }
}
