//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pratica
    {
        public System.Guid IdPratica { get; set; }
        public System.Guid IdSocio { get; set; }
        public int IdSportello { get; set; }
        public System.DateTime DataPratica { get; set; }
        public int IdTipologiaPratica { get; set; }
        public string DescrizionePratica { get; set; }
        public int IdStatoPratica { get; set; }
        public string DescrizioneRiscontro { get; set; }
    
        public virtual Socio Socio { get; set; }
        public virtual Sportello Sportello { get; set; }
        public virtual StatoPratica StatoPratica { get; set; }
        public virtual TipologiaPratica TipologiaPratica { get; set; }
    }
}
