//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rinnovo
    {
        public System.Guid IdRinnovo { get; set; }
        public System.Guid IdSocio { get; set; }
        public System.DateTime Data { get; set; }
        public Nullable<int> Anno1 { get; set; }
        public Nullable<int> Anno2 { get; set; }
        public float QuotaIscrizione { get; set; }
    
        public virtual Socio Socio { get; set; }
    }
}
