//------------------------------------------------------------------------------
// <auto-generated>
//     Codice generato da un modello.
//
//     Le modifiche manuali a questo file potrebbero causare un comportamento imprevisto dell'applicazione.
//     Se il codice viene rigenerato, le modifiche manuali al file verranno sovrascritte.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MDC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Socio
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Socio()
        {
            this.Consulenza = new HashSet<Consulenza>();
            this.Pratica = new HashSet<Pratica>();
            this.Rinnovo = new HashSet<Rinnovo>();
        }
    
        public System.Guid IdSocio { get; set; }
        public string CodiceFiscale { get; set; }
        public string Nome { get; set; }
        public string Cognome { get; set; }
        public Nullable<System.DateTime> DataNascita { get; set; }
        public Nullable<int> IdComuneNascita { get; set; }
        public string Sesso { get; set; }
        public System.DateTime DataIscrizione { get; set; }
        public string Email { get; set; }
        public string Telefono1 { get; set; }
        public string Telefono2 { get; set; }
        public string IndirizzoResidenza { get; set; }
        public Nullable<int> IdComuneResidenza { get; set; }
        public string Cap { get; set; }
    
        public virtual Comune ComuneN { get; set; }
        public virtual Comune ComuneR { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Consulenza> Consulenza { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Pratica> Pratica { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rinnovo> Rinnovo { get; set; }
    }
}
